const sampleTemples = [
  {
    name: 'Sri Venkateswara Temple',
    description: 'One of the most famous temples in India, located in Tirupati.',
    address: 'Tirumala, Tirupati, Andhra Pradesh, India',
    country_id: 'IN',
    state_id: 'AP',
    establishment_year: 1130,
    significance: 'Major pilgrimage center for Hindus.',
    visiting_hours: '4 AM - 10 PM',
    entry_fee: 'Free (Special Darshan tickets available)',
    contact_info: '+91 877 2277777',
    image_urls: ['https://upload.wikimedia.org/wikipedia/commons/3/3e/Tirumala_Venkateswara_Temple.jpg'],
    location: { type: 'Point', coordinates: [79.4192, 13.6288] }, 
  },
  {
    name: 'Meenakshi Amman Temple',
    description: 'Historic temple in Madurai with stunning Dravidian architecture.',
    address: 'Madurai Main, Madurai, Tamil Nadu, India',
    country_id: 'IN',
    state_id: 'TN',
    establishment_year: 1550,
    significance: 'Dedicated to goddess Meenakshi, symbol of Tamil culture.',
    visiting_hours: '5 AM - 12:30 PM, 4 PM - 9:30 PM',
    entry_fee: 'Free',
    contact_info: '+91 452 2344360',
    image_urls: ['https://upload.wikimedia.org/wikipedia/commons/8/8f/Meenakshi_temple_panorama.jpg'],
    location: { type: 'Point', coordinates: [78.1198, 9.9195] },
  },
  {
    name: 'Somnath Temple',
    description: 'One of the twelve Jyotirlinga shrines of Shiva, rebuilt multiple times.',
    address: 'Somnath, Prabhas Patan, Gujarat, India',
    country_id: 'IN',
    state_id: 'GJ',
    establishment_year: 1951,
    significance: 'Important pilgrimage for Shaivites.',
    visiting_hours: '6 AM - 9 PM',
    entry_fee: 'Free',
    contact_info: '+91 2876 231212',
    image_urls: ['https://upload.wikimedia.org/wikipedia/commons/6/6d/Somnath_temple.jpg'],
    location: { type: 'Point', coordinates: [70.4012, 20.8880] },
  },
  {
    name: 'Golden Temple (Harmandir Sahib)',
    description: 'Spiritual center of Sikhism, famous for its golden facade.',
    address: 'Golden Temple Rd, Atta Mandi, Katra Ahluwalia, Amritsar, Punjab, India',
    country_id: 'IN',
    state_id: 'PB',
    establishment_year: 1604,
    significance: 'Most important pilgrimage site for Sikhs.',
    visiting_hours: 'Open 24 hours',
    entry_fee: 'Free',
    contact_info: '+91 183 2553957',
    image_urls: ['https://upload.wikimedia.org/wikipedia/commons/3/3a/Golden_Temple%2C_Amritsar.jpg'],
    location: { type: 'Point', coordinates: [74.8765, 31.6200] },
  },
  {
    name: 'Kashi Vishwanath Temple',
    description: 'Famous Shiva temple in Varanasi, a Jyotirlinga shrine.',
    address: 'Lahori Tola, Varanasi, Uttar Pradesh, India',
    country_id: 'IN',
    state_id: 'UP',
    establishment_year: 1780,
    significance: 'Sacred center of Shaivism and Varanasi’s spiritual life.',
    visiting_hours: '4 AM - 11 PM',
    entry_fee: 'Free',
    contact_info: '+91 542 2392629',
    image_urls: ['https://upload.wikimedia.org/wikipedia/commons/7/79/Kashi_Vishwanath_Temple%2C_Varanasi.jpg'],
    location: { type: 'Point', coordinates: [83.0095, 25.3109] },
  },
  {
    name: 'Jagannath Temple',
    description: 'Historic temple in Puri dedicated to Lord Jagannath.',
    address: 'Grand Rd, Puri, Odisha, India',
    country_id: 'IN',
    state_id: 'OD',
    establishment_year: 1161,
    significance: 'Famous for the annual Rath Yatra.',
    visiting_hours: '5 AM - 11 PM',
    entry_fee: 'Free',
    contact_info: '+91 6752 222001',
    image_urls: ['https://upload.wikimedia.org/wikipedia/commons/f/f9/Jagannath_Temple%2C_Puri.jpg'],
    location: { type: 'Point', coordinates: [85.8312, 19.8083] },
  },
];
